name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Azure Container Registry
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure Container Registry Docker login
        run: |
          az acr login --name zeropaperacr

      - name: Build and tag the Docker image
        env:
          TIMESTAMP: ${{ github.run_id }}-${{ github.run_number }}
        run: |
          docker build . --file app/Dockerfile --tag zeropaperacr.azurecr.io/dev:${{ env.TIMESTAMP }}

      - name: Push the Docker image to ACR
        env:
          TIMESTAMP: ${{ github.run_id }}-${{ github.run_number }}
        run: |
          docker push zeropaperacr.azurecr.io/dev:${{ env.TIMESTAMP }}

